### ISSUE TITLE
作者您好，使用时遇到问题

### ISSUE THREAD

**Issue by tengzhexiao** [anshengme/sentry-dingding#5]
您好，我把钉钉插件安装成功后，testplugin没问题，但是实际上报错误通过worker推送的时候报了以下错误：[ERROR] celery.worker.job: Task sentry.tasks.post_process.post_process_group[65b7bd1e-831a-45d4-b7b5-bd084f02e629] raised unexpected: KeyError(u'DingDing',) (data={u'hostname': 'celery@8da040384cfa', u'name': 'sentry.tasks.post_process.post_process_group', u'args': '[]', u'internal': False, u'kwargs': "{'group': <Group at 0x7f5f08d12b10: id=61L, project_id=2L>, 'is_new_group_environment': True, 'is_new': True, 'event': <Event at 0x7f5f08d12390: id=437L, project_id=2L, group_id=61L>, 'is_regression': False, 'is_sample': False, 'primary_hash': 'b902e38905062abf9dfd76d889763a38'}", u'id': '65b7bd1e-831a-45d4-b7b5-bd084f02e629'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/post_process.py", line 90, in post_process_group
    for callback, futures in rp.apply():
  File "/usr/local/lib/python2.7/site-packages/sentry/rules/processor.py", line 153, in apply
    self.apply_rule(rule)
  File "/usr/local/lib/python2.7/site-packages/sentry/rules/processor.py", line 141, in apply_rule
    for future in results:
  File "/usr/local/lib/python2.7/site-packages/sentry/rules/actions/notify_event_service.py", line 53, in after
    plugin = plugins.get(service)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/base/manager.py", line 62, in get
    raise KeyError(slug)
KeyError: u'DingDing'
能否帮忙看下是什么问题...
环境如下：
服务器版本
9.0.0
Python版本
2.7.15 (default, Oct 16 2018, 08:11:14) 
[GCC 4.9.2]

**Comment by 0xhhhhh** [comment]
安装完成之后重启一下worker和cron试下
