### ISSUE TITLE
9.0.0安装插件后，没有显示插件，已经重启了

### ISSUE THREAD

**Issue by rabbitLove520** [anshengme/sentry-dingding#6]
我是用docker安装的，日志提示
````
Failed to load plugin 'sentry_dingding':
cron_1       | Traceback (most recent call last):
cron_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 31, in register_plugins
cron_1       |     plugin = ep.load()
cron_1       |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
cron_1       |     self.require(*args, **kwargs)
cron_1       |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2347, in require
cron_1       |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
cron_1       |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
cron_1       |     raise VersionConflict(dist, req).with_context(dependent_req)
cron_1       | ContextualVersionConflict: (redis 2.10.5 (/usr/local/lib/python2.7/site-packages), Requirement.parse('redis>=2.10.6'), set(['redis-py-cluster']))
````

**Comment by wujunze** [comment]
兄弟  你的问题解决了吗
